model:
  model_name: ASRLLM
  file: models/model.py:ASRLLM
  modal: audio
  encoder_type: finetune

  # LLM settings
  llm_model_name: llama3.2-3B
  llm_model: meta-llama/Llama-3.2-3B
  llm_model_path: null
  llm_type: decoder_only
  llm_dim: 3072
  
  # Encoder settings
  encoder_model_name: openai/whisper-base
  encoder_dim: 512

  # Projector settings
  projector: linear
  mel_size: 80           # mel bins
  normalize: false
  mel_time_stride: 8     # tokens every 8 frames (controls sequence length)
  projector_ds_rate: 2   # each token sees 8*2=16 frames of context (receptive field)
  mel_input_norm: true  # e.g., log-mel + per-bin mean/var norm if true
  mel_dropout: 0.1       # dropout on projected tokens; try 0.0–0.1 if overfitting

train:
  model_name: ASRLLM
  run_validation: true
  batch_size: 6                  # micro-batch per GPU
  batching_strategy: packing
  context_length: 384             # balance speed/quality on 3B
  gradient_accumulation_steps: 2  # effective batch ≈ 32
  grad_clip: 1.0
  num_epochs: 15                  
  num_workers: 8
  validation_interval: 1000       # validate each epoch via your loop
  lr: 1.0e-4
  weight_decay: 0.01
  gamma: 0.85
  seed: 42
  use_fp16: false                 # prefer bf16 on A6000
  mixed_precision: true
  val_batch_size: 5               # larger no-grad batches speed up eval

  # Training options
  use_peft: false
  output_dir: outputs_3b_enc_lin_proj_20h/
  freeze_layers: false
  num_freeze_layers: 0
  quantization: false
  one_gpu: true
  save_model: true
  use_fast_kernels: false         # set SDPA in code
  freeze_llm: true                # projector-only
  freeze_encoder: true

  # Learning rate scheduler settings
  lr_scheduler: cosine_warmup # linear_warmup, cosine_warmup
  warmup_steps: 500  # 2-5% of total steps
  num_cycles: 0.5  # only for cosine scheduler

  # Early stopping settings
  es_enabled: false
  mode: min
  patience: 5
  min_delta: 0.001
  wer_min_delta: 0.002

data:
  dataset: speech_dataset
  file: datamodules/datasets.py:get_speech_dataset
  train_data_path: data/train-clean-20.jsonl
  val_data_path: data/dev-clean.jsonl
  test_data_path: data/test-clean.jsonl
  train_split: train
  val_split: val
  test_split: test
  prompt: null
  data_path: null
  max_words: null
  max_mel: null
  fix_length_audio: -1
  inference_mode: false
  input_type: mel
  mel_size: 80
  normalize: false

log:
  use_wandb: true
  wandb_dir: ./wandb
  wandb_entity_name: ASRLLM
  wandb_project_name: ASRLLM_llama_3B_20h
  wandb_exp_name: exp_3b_enc_lin_proj
  log_dir: ./logs
  log_filename: train_3b_enc_lin_proj_20h.log
  log_interval: 100
